Repository AY2324S2-CS2113-T12-4/tp, pull requests merged in 2024-04, with the labels that each got.

#110 Update user guide features section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  omni.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/TravelActivityList.java
Labels: documentation, priority.High

#111 add sequence diagram for tag function
  docs/DeveloperGuide.md
  docs/TagSequenceDiagram.png
  docs/team/TagSequenceDiagram.puml
Labels: documentation

#114 Throw exception class
  mylog.txt
  omni.txt
  src/main/java/seedu/duke/CheckParameters.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
Labels: priority.High

#116 Fix bug
  omni.txt
  src/main/java/seedu/duke/Accommodation.java
  src/main/java/seedu/duke/FileSave.java
  src/main/java/seedu/duke/Food.java
  src/main/java/seedu/duke/Landmark.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/TravelActivity.java
  src/main/java/seedu/duke/TravelActivityList.java
  src/main/java/seedu/duke/Ui.java
  src/test/java/seedu/duke/DukeTest.java
Labels: type.Enhancement

#118 extract log method and save file
  omni.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FileSave.java
  src/main/java/seedu/duke/TravelActivityList.java
Labels: documentation

#120 update userguide
  docs/UserGuide.md
Labels: documentation

#123 Update userguide
  docs/UserGuide.md
  omni.txt
Labels: documentation, priority.High

#125 update user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  omni.txt
  src/main/java/seedu/omnitravel/storage/FileSave.java
Labels: documentation

#134 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation

#192 Bug fixes for PED
  docs/UserGuide.md
  omni.txt
  src/main/java/seedu/omnitravel/errorhandlers/CheckParameters.java
  src/main/java/seedu/omnitravel/omnitravel/OmniTravel.java
  src/main/java/seedu/omnitravel/parser/Parser.java
  src/main/java/seedu/omnitravel/storage/FileSave.java
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivity.java
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivityList.java
  src/main/java/seedu/omnitravel/ui/Ui.java
  src/test/java/seedu/omnitravel/OmniTravelTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#197 Add Junit test for parser class
  src/main/java/seedu/omnitravel/exchangerateapi/CurrencyRate.java
  src/main/java/seedu/omnitravel/omnitravel/OmniTravel.java
  src/main/java/seedu/omnitravel/parser/Parser.java
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivityList.java
  src/main/java/seedu/omnitravel/ui/Ui.java
  src/test/java/seedu/omnitravel/OmniTravelTest.java
Labels: type.Task, priority.High

#200 Bug fix and userguide update
  docs/UserGuide.md
  src/main/java/seedu/omnitravel/errorhandlers/CheckParameters.java
  src/main/java/seedu/omnitravel/omnitravel/OmniTravel.java
Labels: type.Bug

#206 Update UserGuide for clarity
  docs/UserGuide.md
  omni.txt
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivityList.java
  src/test/java/seedu/omnitravel/OmniTravelTest.java
Labels: documentation

#207 Added PPP
  docs/team/eugenechanjiajun.md
  src/main/java/seedu/omnitravel/errorhandlers/CheckParameters.java
  src/main/java/seedu/omnitravel/parser/Parser.java
  src/test/java/seedu/omnitravel/OmniTravelTest.java
Labels: documentation

#209 Branch ppp
  docs/team/daryltay415.md
  omni.txt
Labels: documentation

#213 Bug fix @ChinYanXu
  omni.txt
  src/main/java/seedu/omnitravel/parser/Parser.java
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivityList.java
  src/main/java/seedu/omnitravel/ui/Ui.java
Labels: type.Bug

#212 update userguide for clarity
  docs/UserGuide.md
  docs/team/chenkangg.md
  omni.txt
Labels: documentation

#225 Update Junit tests
  src/test/java/seedu/omnitravel/OmniTravelTest.java
Labels: type.Task, priority.High

#226 update docs + add assertion, loggers
  docs/team/chenkangg.md
  src/main/java/seedu/omnitravel/parser/Parser.java
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivity.java
  src/main/java/seedu/omnitravel/travelactivitytypes/TravelActivityList.java
  src/main/java/seedu/omnitravel/ui/Ui.java
Labels: documentation

#227 update PPP
  docs/team/eugenechanjiajun.md
Labels: documentation

#228 Update developer guide
  docs/ArchitectureDiagram.png
  docs/DeveloperGuide.md
  docs/Errorhandler.png
  docs/TravelActivityTypeClassDiagram.png
  docs/UpdateFeatureClassDiagram.png
  docs/team/ArchitectureDiagram.puml
  docs/team/Errorhandler.puml
  docs/team/TravelActivityTypeClassDiagram.puml
  docs/team/UpdateFeatureClassDiagram.puml
Labels: documentation

#229 Finalise UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img_3.png
  docs/team/FileSaveUML.puml
Labels: documentation

#230 Update PPP
  docs/team/eugenechanjiajun.md
Labels: documentation

#232 update ppp
  docs/team/chenkangg.md
Labels: documentation

#238 Fix developer guide sequence diagram
  docs/DiagramImages/img_1.png
  docs/UserGuide.md
  docs/plantUML diagrams/UpdateSequenceDiagram.puml
Labels: documentation

#239 Update sequence diagram for save function
  docs/DiagramImages/img.png
  docs/plantUML diagrams/FileSaveSequence.puml
  src/main/java/seedu/omnitravel/parser/Parser.java
Labels: documentation

#242 Update PPP
  docs/team/eugenechanjiajun.md
Labels: documentation
