Repository AY2324S2-CS2113-T12-4/tp, pull requests merged in 2024-03, with the labels that each got.

#53 Add tag and untag functions
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/TravelActivity.java
  src/main/java/seedu/duke/TravelActivityList.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High

#85 Add save function
  src/main/java/seedu/duke/Accommodation.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FileSave.java
  src/main/java/seedu/duke/Food.java
  src/main/java/seedu/duke/Landmark.java
  src/main/java/seedu/duke/TravelActivity.java
  src/main/java/seedu/duke/TravelActivityList.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High

#88 Activity type parser
  omni.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#97 Implement expense functions + update developerGuide
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/TravelActivity.java
  src/main/java/seedu/duke/TravelActivityList.java
  src/test/java/seedu/duke/DukeTest.java
Labels: documentation, priority.High

#100 Load save file and find function bug fix and Designer Guide update
  docs/DeveloperGuide.md
  docs/img.png
  docs/img_1.png
  docs/team/FileSaveSequence.puml
  omni.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FileSave.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/TravelActivityList.java
  src/test/java/seedu/duke/DukeTest.java
Labels: documentation, priority.High

#107 update Userguide + helpCommand
  docs/UserGuide.md
  src/main/java/seedu/duke/Ui.java
Labels: documentation

#108 Reduced method size to improve code readability + fix indentations
  omni.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/FileSave.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
Labels: bug, type.Task, priority.High
